title: Галина Харнахоева
description: [Портфолио Data Science проектов]
author: Галина Харнахоева
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 
social-network-links:
  telegram: kharnakhoeva
